"""
export_c_array.py — emit a .tflite blob as a C header for TFLite Micro.

Produces the same shape of artifact as drongonet's deploy/drongonet-micro.h: a
16-byte-aligned const array plus its length, ready to hand to
tflite::GetModel(sparrownet_model_data).

The header also records the model's quantization parameters and input geometry as
comments, because the firmware side has to reproduce the exact same preprocessing
(resample 16 kHz, n_fft=1024, hop=256, mel, power_to_db ref=max top_db=80, per-clip
min-max, then quantize with the input scale/zero-point printed here). Getting any of
that wrong silently degrades accuracy on-device with no error.

Usage:
    python deploy/export_c_array.py results/<tag>/sparrownet_int8.tflite \
        -o deploy/sparrownet-micro.h
"""

import os
import sys
import argparse
import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import tensorflow as tf

from config import (
    SAMPLE_RATE, N_FFT, HOP_LENGTH, FMIN, FMAX,
    SIZE_SOFT_LIMIT_BYTES, SIZE_HARD_LIMIT_BYTES,
)


def model_metadata(path):
    interp = tf.lite.Interpreter(model_path=path)
    interp.allocate_tensors()
    inp = interp.get_input_details()[0]
    out = interp.get_output_details()[0]
    return {
        "input_shape": [int(v) for v in inp["shape"]],
        "input_dtype": str(inp["dtype"].__name__),
        "input_scale": float(inp["quantization"][0]),
        "input_zero_point": int(inp["quantization"][1]),
        "output_shape": [int(v) for v in out["shape"]],
        "output_scale": float(out["quantization"][0]),
        "output_zero_point": int(out["quantization"][1]),
    }


def to_header(tflite_path, var_name="sparrownet_model_data", guard=None):
    with open(tflite_path, "rb") as f:
        blob = f.read()
    meta = model_metadata(tflite_path)
    n_mels = meta["input_shape"][2]
    guard = guard or (var_name.upper() + "_H")

    lines = []
    a = lines.append
    a(f"// Generated by deploy/export_c_array.py on "
      f"{datetime.date.today().isoformat()}")
    a(f"// Source: {os.path.basename(tflite_path)}  ({len(blob)} bytes, "
      f"{len(blob)/1024:.2f} KB)")
    a(f"// Budget: soft {SIZE_SOFT_LIMIT_BYTES/1024:.0f} KB / "
      f"hard {SIZE_HARD_LIMIT_BYTES/1024:.0f} KB -> "
      f"{'OK' if len(blob) <= SIZE_SOFT_LIMIT_BYTES else ('OVER SOFT' if len(blob) <= SIZE_HARD_LIMIT_BYTES else 'OVER HARD')}")
    a("//")
    a("// The firmware MUST reproduce this preprocessing exactly:")
    a(f"//   resample to {SAMPLE_RATE} Hz mono")
    a(f"//   STFT n_fft={N_FFT}, hop={HOP_LENGTH}, center=false")
    a(f"//   mel filterbank n_mels={n_mels}, fmin={FMIN:.0f}, fmax={FMAX:.0f}")
    a("//   power_to_db(ref=max, top_db=80) then per-clip min-max to [0,1]")
    a(f"//   quantize: q = round(x / {meta['input_scale']:.10f}) "
      f"+ ({meta['input_zero_point']}), clamped to [-128, 127]")
    a("//")
    a(f"// Input  {meta['input_shape']} {meta['input_dtype']}")
    a(f"// Output {meta['output_shape']}  scale={meta['output_scale']:.10f} "
      f"zero_point={meta['output_zero_point']}")
    a("// Output index 1 is the bird-positive score:")
    a(f"//   p_bird = (out[1] - ({meta['output_zero_point']})) "
      f"* {meta['output_scale']:.10f}")
    a("")
    a(f"#ifndef {guard}")
    a(f"#define {guard}")
    a("")
    a("#include <cstdint>")
    a("")
    a(f"constexpr int {var_name}_len = {len(blob)};")
    a("")
    a("#if defined(__has_attribute)")
    a("#define SPARROWNET_ALIGN(x) __attribute__((aligned(x)))")
    a("#else")
    a("#define SPARROWNET_ALIGN(x)")
    a("#endif")
    a("")
    a(f"const unsigned char {var_name}[] SPARROWNET_ALIGN(16) = {{")
    for i in range(0, len(blob), 12):
        chunk = blob[i:i + 12]
        a("  " + " ".join(f"0x{b:02x}," for b in chunk))
    a("};")
    a("")
    a(f"#endif  // {guard}")
    return "\n".join(lines) + "\n", meta, len(blob)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("tflite")
    ap.add_argument("-o", "--out", default=None)
    ap.add_argument("--var-name", default="sparrownet_model_data")
    args = ap.parse_args()

    header, meta, size = to_header(args.tflite, args.var_name)
    out = args.out or os.path.splitext(args.tflite)[0] + ".h"
    with open(out, "w") as f:
        f.write(header)
    print(f"wrote {out}  ({size} bytes model, {len(header)} bytes header)")
    for k, v in meta.items():
        print(f"  {k}: {v}")
